custom:
  jwt:
    secretKey: euTvPIZ+FDCl3TRtcYpo6EAE3joaXLxuceC5V+rrhAKSZEYpmSl5dWMqpenazk5PRsxtaiimkiyxzfq4DdUpgQ==
    accessToken:
      expirationSeconds: 600
    refreshToken:
      expirationSeconds: 86400
